version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landingpage
    restart: always
    ports:
      - "3001:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: production

networks:
  my_network:
    external: true